<?php

/**
 * Implementation of hook_form_alter
 * 
 * This hook alters the text of the "Save" button to become "Comment" instead
 * 
 * $form = nested array that contains the form elements
 * $form_state = current state of the form
 * $form_id = string that refers to the name of the form itself
 */
function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if($form_id == 'comment_comment_form') {
        $form['actions']['submit']['#value'] = t('Comment');
    }
}